---
- name: "Update apt packages"
  become: true
  apt:
    update_cache: "yes"

- name: "Upgrade apt packages"
  become: true
  apt:
    upgrade: "yes"

# - name: Install the gpg key for nodejs LTS
#   apt_key:
#     url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
#     state: present

# https://deb.nodesource.com/setup_14.x

# - name: Install the nodejs LTS repos
#   apt_repository:
#     repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
#     state: present
#     update_cache: yes

# - name: "install dependencies"
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: present
#     update_cache: "yes"

- name: install node 
  shell: |
    curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs


- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory



# - name: Transfer backend files to cloud server
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: "Unarchive backend files"
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend


# - name: make sure the latest npm is installed
#   become: true
#   command: npm install -g n
#   args:
#     chdir: /home/ubuntu/backend

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: "build package"
  become: true
  command: npm run build --if-present
  args:
    chdir: /home/ubuntu/backend

####################
- name: "Execute seeder"
  become: true
  command: npm run data:import
  args:
    chdir: /home/ubuntu/backend

- name: "Executing node"
  become: true
  command: pm2 start npm --name backend -- run start
  args:
    chdir: /home/ubuntu/backend

#####################
